# Site settings
baseurl = "gokhan.io"
canonifyurls = true
languageCode = "en"
title = "Jordan Liu"
theme = "hugo-theme-cactus-plus"
googleAnalytics = "UA-90951528-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
paginate = 20

[outputFormats.MyEnrichedFormat]
protocol = "https://"

[params]
	name = "Jordan Liu"
	job = "Undergraduate Student @ University of Pennsylvania"
	description = "Health Policy, Bioethics, Global Health, Medicine"
	bio = "[R](https://gokhan.io/categories/r) | [Python](https://gokhan.io/categories/python)"

	github = "jdanliu"
	enableRSS = true
	
	title404 = "This is not the web page you are looking for."
	subtitle404 = "Perhaps your father wanted you to browse this page when you were old enough, but your uncle wouldn't allow it. He feared you might follow old Obi-Wan on some damn fool idealistic crusade like your father did..."

	disqusShortname = "gokhancif"
	enableDisqus = true

	enableGoogleAnalytics = true

	custom_css = []
	customJS  = []

	aboutAuthor = "Senior Data Scientist at Attest"

	iconFont = "font-awesome"
  
  shareOnTwitter = true

  shareOnFacebook = true

[social]

  github-square = "https://github.com/jdanliu"
  linkedin = "https://www.linkedin.com/in/jordan-l-b76582120/"
  facebook = "https://www.facebook.com/jdanliu"
